### ISSUE TITLE
[REQUEST] Support for vshufpd on Zen3

### ISSUE THREAD

**Issue by TiborGY** [RRZE-HPC/OSACA#111]
**Is your feature request related to a problem? Please describe.**
OSACA does not support vshufpd on Zen3, "performance data is missing".

**Describe the solution you'd like**
Performance data for vshufpd added

**Describe alternatives you've considered**
Using LLVM-MCA

**Additional context**
https://godbolt.org/z/azT7q7hs8

**Comment by JanLJL** [comment]
Hi @TiborGY ,

I measured and added the `vshufpd` and `vshufps` instructions for Zen3 and Zen4 in commit 94e90e292c1c29cc98bf1d8896f515dbeeae49ea, which will be online on godbolt with the next release (0.6.2).

Best,
Jan
