### ISSUE TITLE
elf64 only?

### ISSUE THREAD

**Issue by cod3monk** [RRZE-HPC/OSACA#15]
OSACA is currently checking if a binary is an elf64 binary in `osaca.check_elffile()`. Is that really necessary? What are the elf64 specifics that we rely on or could this restriction be lifted? (note that my mac produces Mach-O binaries and objdump is able to decode those)

**Comment by JanLJL** [comment]
I still wasn't able to check against that on a Mac, I'm sorry! OSACA on Linux checks for elf64 binaries to make sure the file was compiled with `-g`. This is needed for interleaving high level code and assembly to check for the OSACA high level code markers.

I will try to get back to you as soon as possible.

**Comment by cod3monk** [comment]
Not really an urgent issue. I am also contemplating the idea to drop the binary analysis altogether, since it highly dependent on specific `objdump` versions and likely to cause a lot of compatibility issues, without providing much benefit.

**Comment by cod3monk** [comment]
solved in new version (dev releases are available)
