### ISSUE TITLE
inspect_with_iaca() machine readability and statelessness

### ISSUE THREAD

**Issue by cod3monk** [RRZE-HPC/OSACA#16]
I would like to use the `OSACA.inspect_with_iaca()` or a similar high-level function as an API, but this is currently not very usable due to two reasons:
1. the result is a string, which is directly output to stdout.
I would need a machine readable output, which is separate from the output formatting.

2. running this function multiple times multiplies the output length
there should not be an internal state that breaks if this is run several times. either generate it always on-the-fly or overwrite the internal state on regeneration.

**Comment by JanLJL** [comment]
Hi @cod3monk ,
I implemented a basic version for machine readability in 822e1ef3007d3dca1d14ab725b89e903ede0be1b by calling OSACA from command line with `-l` or `--list-output` flag or  - in your case - by calling `OSACA.inspect_with_iaca()` after setting the `machine_readable` attribute, e.g.:

``` python
  osaca = Osaca('ARCH', '/link/to/assembly.s')
  osaca.machine_readable = true
  output = osaca.inspect_with_iaca()
```

#### Background
The output is a list with `#instruction_forms` elements and is structured as followed: Each instruction form (= line in the assembly code) is one list element in the overall list. The element is a list itself with `#port+1` elements (separately listed pipes like the divider pipe count extra, comparable to the human readable output) , containing the port occupation of the instruction form and - as last element - the instruction form itself. This again is a list, combined out of the the mnemonic, the parameters (as `OSACA.Param` objects) and the whole instruction form as string. 

#### Example
The previous output 

```
|  0   -  DV  |  1   |  2   |  3   |  4   |  5   |  6   |  7   |
----------------------------------------------------------------
| 0.50        | 0.50 | 0.50 | 0.50 |      |      |      |      | vaddsd    16(%r14,%r15,8), %xmm2, %xmm3
```

would now look like this:

```
[[0.5, 0, 0.5, 0.5, 0.5, 0, 0, 0, 0, ['vaddsd', <osaca.param.Register object at 0x7f014e892358>, <osaca.param.Register object at 0x7f014e8a2390>, <osaca.param.MemAddr object at 0x7f014e8927f0>, 'vaddsd    16(%r14,%r15,8), %xmm2, %xmm3']]
```

Let me know what you think and if this could work for your purposes, I'm open for any suggestions or changes if there's a more convenient way for you.

**Comment by cod3monk** [comment]
Ah, I think this is an misunderstanding:
I want to use OSACA as a library, without going through the command line and string parsing.

To do that functionality in the OSACA class will need to provide separated functions for analysis and output and should not break if multiple output formats are requested for the same analysis. I am working on it in the api_cleanup branch.

The changes you made in 822e1ef are useful in getting there. Thanks!

**Comment by JanLJL** [comment]
This was realized with more generic functions in `osaca.py` and with the Kerncraft API accessible via 
```
from osaca.api import KerncraftAPI
```
