### ISSUE TITLE
OSACA doesn't recognize immediate to memory instructions

### ISSUE THREAD

**Issue by ychen306** [RRZE-HPC/OSACA#33]
```
                    Ports Pressure in cycles
|  0   | 0DV  |  1   |  2   |  3   |  4   |  5   |  6   |  7   |
----------------------------------------------------------------
|      |      |      |      |      |      |      |      |      | X addl $1, 8(%rax)
```
It recognizes the instruction when you remove the `l` suffix. But the issue is `addl $1, 8(%rax)` is the *only* way to write this instruction -- `gas` refuses to assemble `add $1, 8(%rax)` because the `add` is ambiguous.

**Comment by JanLJL** [comment]
If an instruction form is not part of the (local) OSACA database, you can add it by using the automatically created micro benchmark file in `~/.osaca/benchmarks/`. In your case there should be a `addl-mem-imd.S` and `addl-mem_imd-TP.S` to measure the latency and the throughput, respectively. After measuring using [ibench](https://github.com/hofm/ibench), OSACA can include the measured results using the `--include-ibench` flag. Please have a look at the [example section](https://github.com/RRZE-HPC/OSACA#example) of the README for more details.

However, if you cannot benchmark your instruction, I recommend you in your case to add the instruction form manually. Open the csv file for your specific architecture at `~/.osaca/data/`, copy the line for the `add-mem_imd` instruction form and change the mnemonic in the new line from `add` to `addl`, the throughput and latency should be the same.

Either way, as soon as the instruction form is added to the database file, OSACA should recognize it in the next run.
