### ISSUE TITLE
Provide pickles in Pypi release

### ISSUE THREAD

**Issue by JanLJL** [RRZE-HPC/OSACA#53]
The first OSACA analysis for a micro-arch after installing currently includes the read-in of the yaml file and only after that OSACA benefits from the fast cached pickle reuse.
Since most of the users don't adjust the data files before the first run, it might be beneficial to add the pickle files to the Pypi release to speedup the first run.
Of course it is necessary to check the module does not get blown up too much through this.

**Comment by cod3monk** [comment]
See commits a6cb09cf1fc1e474593fa112574f1eae0827f58a and 9d2ea8603f706cdddf240ce64b9286db488d5977
