### ISSUE TITLE
Error during installation related to building bdist wheel

### ISSUE THREAD

**Issue by apmorton** [RRZE-HPC/OSACA#54]
simply `pip install osaca` on a system without the requisite dependencies already installed (pyparsing, ruamel.yaml, etc):
```
  Build ISA and architecture cache
  Traceback (most recent call last):
    File "_build_cache.py", line 7, in <module>
      from osaca.semantics.hw_model import MachineModel
    File "../../osaca/semantics/__init__.py", line 6, in <module>
      from .isa_semantics import ISASemantics, INSTR_FLAGS
    File "../../osaca/semantics/isa_semantics.py", line 5, in <module>
      from osaca.parser import AttrDict, ParserAArch64, ParserX86ATT
    File "../../osaca/parser/__init__.py", line 8, in <module>
      from .parser_x86att import ParserX86ATT
    File "../../osaca/parser/parser_x86att.py", line 5, in <module>
      import pyparsing as pp
  ModuleNotFoundError: No module named 'pyparsing'
```

the install succeeds, but not using a bdist (and this ISA/architecture cache is not built)

**Comment by JanLJL** [comment]
Hi @apmorton,
apparently sometimes the order of installing dependencies and importing them for building the cache is not kept.
This is not always the case, we needed to re-install OSACA on several machines to be able to reproduce that error...

I uploaded a bdist_wheel to PyPI, so for now you should not have any problem anymore and we will improve the cache build process in the next release, thank you for pointing this out!
