### ISSUE TITLE
Testcase not helpful

### ISSUE THREAD

**Issue by cod3monk** [RRZE-HPC/OSACA#6]
As seen in https://travis-ci.com/RRZE-HPC/OSACA/builds/56366538, the first tox test case checks out, but does not print any useful data. The test case should therefore really check that the expected output is generated, not just that the command returned a valid exit code.

**Comment by JanLJL** [comment]
By now we have separated tests for just checking for a valid exit code (e.g., in `/tests/test_cli.py`) and for the semantics of the output (e.g., `/tests/test_semantics.py`).
Therefore, I will close this issue.
