### ISSUE TITLE
Import asmbench result

### ISSUE THREAD

**Issue by ghisloine** [RRZE-HPC/OSACA#76]
Hello, i read README.md many times but i can't understand how can i import asmbench result to osaca ? In asmbench side, i ran python3 -m asmbench.sc18src command and it prints out some th and latency values to terminal. 

1) ASMBENCH does not create a DB if i understand true ? 
2) Should i create a file for my own ?

**Comment by cod3monk** [comment]
1. yes, asmbench does not create a database
2. yes, you will need to create it on your own

`python3 -m asmbench` is the more general interface and allows you to measure individual instructions and pairs of instructions.

Feel free to reopen if more questions arise.
