### ISSUE TITLE
iacaMarks.h compatibility

### ISSUE THREAD

**Issue by hpcbern** [RRZE-HPC/OSACA#88]
Looking at iacaMarks.h for IACA version 2.1, 2.2, 2.3 and 3.0,
there's
```
$ tail iacaMarks.h
/**************** asm *****************
;START_MARKER
mov ebx, 111
db 0x64, 0x67, 0x90

;END_MARKER
mov ebx, 222
db 0x64, 0x67, 0x90

**************************************/
```
which leads (e.g. using `gcc -S`) to
```
          movl $111, %ebx
          .byte 0x64, 0x67, 0x90
```
and
```
          movl $222, %ebx
          .byte 0x64, 0x67, 0x90
```

which corresponds to the `find_marked_kernel_x86ATT`
```
nop_bytes = ["100", "103", "144"]
```
(cmp. [marker_utils, line 58](https://github.com/RRZE-HPC/OSACA/blob/0de00e512b200bcc504647b17977c4974231be28/osaca/semantics/marker_utils.py#L58))

In this context, the OSACA parser seems not to be aware of the hex-notation
and that 0x64 is equal to 100, etc.
Looking at `match_bytes` there's a just a string comparison
```
if extracted_bytes[0 : len(byte_list)] == byte_list:
```
(cmp. [marker_utils, line 191](https://github.com/RRZE-HPC/OSACA/blob/0de00e512b200bcc504647b17977c4974231be28/osaca/semantics/marker_utils.py#L191))
and unfortunately (['0x64', '0x67', '0x90'] != ['100', '103', '144'])
the markers are not found.

They have to be manually converted from hexadecimal to decimal
or (alternatively) the -l Option to manually set the lines range has to be used.

A quick hack could be just to replace the match_bytes line 191 (see above) with
```
if all([int(e1,0) == int(e2,0) for e1, e2 in zip(extracted_bytes[0 : len(byte_list)], byte_list)]):
```
Maybe converting and storing (& comparing) bytes as integers instead of strings might be another option.

**Comment by JanLJL** [comment]
Hi @hpcbern,
This should be fixed now and on PyPI with the next release.
If not, please feel to reopen the issue.
