### ISSUE TITLE
OSACA fails on godbolt.org with KeyError: "Port 'D' not in port list."

### ISSUE THREAD

**Issue by TiborGY** [RRZE-HPC/OSACA#93]
Dear devs,

I have been playing with godbolt, trying all the new tools and whatnot, and I have found that OSACA crashes with `KeyError: "Port 'D' not in port list."`.
Now, I am not entirely sure if this should be reported to the godbolt repo or here, but at first glance it feels like more of a tool issue.

See [this link for error](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIAKykrgAyeAyYAHI%2BAEaYxCAA7NIADqgKhE4MHt6%2BAaSp6Y4CoeFRLLHxSbaY9kUMQgRMxATZPn6BdpgOmQ1NBCWRMXGJ0gqNza25HeP9YYPlw0kAlLaoXsTI7BzmAMxhyN5YANQmO24Abl1ExKfYJhoAgrv7h5gnZ8hj%2BIK3909mewYBy8x1ObmQLCYBAQv0ezyBr3ebjGxDCwFhT0eAHoscA8JcjphLsQAJ5HBReZKpZqYdDkkljTAsI4EEnJN5MI5eBh4ACOXjeDB8cTwyCOeCwgjwNDifxx0LwCnFSqIR1iRyY0XoLNQ5JqV3xNTJaBYyTobwEtDJ0LeVG53QEKoQUI1xEFmFptNIRxIGoIR3oTDGGvOqAlGtotCOxG5jjYR2QCC6AGsFH9dlgaOEjspsEIAPoADR2AE0uAAtLhyLhHLjpgGZuY5vNFyQlsyVo5mes7RvZ3MFwv%2BdudnY9vtvAdFgBsI5rknHmCzk5bhbbFarNf8i%2BXzcHpY7NenO6bU6HZcr1aOCRP/dX687AA509isQR1uE6TajswxmTkm6AGoJsCgKL6zrIMm4qCLqLBeImP6inERxuNY1hcAkCaOgQmCqABRx2kCdRpq%2BAAqADyAAi5EgAmzpGG8NrMqqaAMIy5xiEcADuSYMChaGWGYGhYWwSpNGsDDoH8rGMnhxBqqgnhHAAkgoQgMjhLAWMQTCsGplLUjh6AQEsJgJFYcIaAAnDiWJuu%2BxBsSyMZvNKLJJgm6xuoI9KMsxbKuUqFJUiQRlHOceCct%2BFhBo4hhHNpul6XuAZ4NEOmkt6VBiEoPo2sQXGKpgL5WW5Mk4XJRwQFOQglkIpHYAAsvmpElrm7yUaclF7kWpYbtWSzRpgDl8QQLmnBZmKlVQWFsRV%2BHVS2tX1U1LVtdgHVdT1a4Xpug32R%2BzkChNJVldhuELTVdUNc1rXtV1W1ng%2BXD7cNh1jcdOyTfc02zbJl1Lddq13RtD07N1T1zq9I1HcVX2nTN5UXfJi0FstN1rfd4OPauw6HtD73jfDlm/UjlWo/m6PA%2Btm3g9tB6VgTjmwydJNnXNyNVVdK23TTYMQ7ju0DUNMMfXD33WQdzPZbQSis08CSdZZDxk/hXhhAQOxmPm/rAMkChoG6JlmRLNk4obby0KgeJiqgM0AOLDcocQsOpLAsMbbOI%2Bd5PcxjIO0wL%2B5Cy9IuHcexNTez/0o371NY51dNngzodS3xXDdpHP3R/NseAzzmOg9jSf3iHTN8WYC5Z9ZOecxTVO8wnOODs95ddlXpu177%2Bf%2B3zxdB62UNh8zkjPtXpM%2BwDaNA43ReJwP5748PFeSBo8vZ97HPd9PBcB/z22zkvae1pIq/rzXm8x1zPfx3PzdFsO/Wp29zMZ2v4/H%2B/32K9Jk/yerggtY6yOI7AgztiCuxJO7Y25kSq2QVEqLiOkqTIUVD%2BD0WA6SxFEF4XKqt5JuXQKgTASoGCoH9PgBQTRmRjChKKDUoE4gECVGEdygpyEAFpGjJkYGqHSQIEBHEoHA%2BUCA0FoLIf6Tk0QvDAG9IQJU6ABQ6jYZ5Yg3l/SoUsNYckjRJJNCwZgNEGojgACpzGmJKvgrkGsgH%2BmUEIDqRw9YGxIJgY249aGOGQPmIMShmjVSEGAMAXUNDenMGYdSfkWQBR/OQoaaBgA8gAF60giaZD%2BL8%2BIOPXj/R41iAGa21rrZgFsYGm1shbAM1t6F2xAcNCIUJUAsAUJ7KOl9c7Xx3r3JuJdg5PzbhHTuHS65x1noHemQ9j5DIRn9Tp9cZ6FwmZDDcgzz4Ty3lPSmiy97922s9YWx8bzjy7lshuSz96QyPlk686zTl526bfZZgtrkwzHsMuZoyb7jMuauQ%2BjNl5HCsnckZ29tm7z7vPbaj9LzPzeesz%2BuSlYqz/jYwBxT6kEEaUQFp5SRFvjEYg5B7ICGkIwbSNUXQmC4LeNYwhxDSHxModQ3RdCxR%2BKYSw0aHlJFcKYDwvi6VDAIWESTeBhLlRxKkWqWR8jmFHCUYxXU35kBeUYJogSFhWX6OIIY4xnILGWJJgU2xGKIgPCcUkpgZSMmmy8aKXxjCAnmuCaE8JZhIkaSZDE9kUqEnWxSWkj1tqSrH3NUil8KsDCgT9M0k2fwjiJqOLZXRbinRvH1GwHyCgoHRCUnU%2BKTTmSGDpAoo4hYSzliwiQb4UISEJqTckLwWpRQgAbYmxMTR6TlE8CYfwFgxz%2BETpNJNCq1hajeKoNANbvQkmnbq70yT51SXHubbCMYHAkBIlHBgtAmxFpMkI7tebaAmzCeesynVYF5J3Xu7MB7yp0S7TmnttB8xhHzFwb0j7O3yRfSe99DB8xmG/dhMdzbtRTsUrqwDoG5rgYnUcOd0H0CwbmQh7US6UOAdMiTH6R7/29vMoRt9H6v3Hs8IB4D3o16K29FBmtEAGMwbCCsJDy6IDIZrThxdHGsPcdY/Gm92dd37pxRAH9zpiCmPQyRtDj6iEQcncu%2BTYHFOIa4yxhgcHgzqcwypwTeHrJHuY8ZUzPH2Moc4wZhgbH%2BO6ogPZ1DhmprxqM1ZEjfaLBryHU4uTYQvM%2BeHSVH6nn%2B11l81tfzDAvMReC%2B5sLFhuyRbpl/ELwmf7VyjX4o4qgSTJJoPQNzFqk0prGGm1R6q8BulmjhQQSoC3kjRNqCt5YOF7p4QRc07ajhNpbcgNtjxR2FLsT%2BItaZI6jr0xm8IxBgAknlqOr4IAQAomMbhMaYg5iLaTctkAlxN03DOEW24saWAHfWSVTSyQDA4SRKydkzA2AADpXtHFIhNu4JM8sFfNM44arWIBea85CEksR8zchpVJIdfbuofde89hVPgWAkmUNa5Mg1H3FZ%2Bj9cVaCgIRSwEqE0yQ6HRDoIQMkhVoSqOAADytBF7R1GgkcOCtBHCtZC5LG5piEGXYy/FzEKLNnyWm0cbAAB1fMAAlRqQhKL5kospeqLVpcPAAGLkXzBaraOxntpfyaisXkv8zq4eG4Ci0unEcK4Pr5N4upey/l4r5XpFVca6108LLYuHg4sooqAgEmwMnbMNOfM%2BY3RrYcOHs75HH0h7DxHkhY1RQEBj0WswplYFiqxKIWgqrbuMQ8pQvRmxKUEC4h6UaXFdTjZ68fPbCheQBL26kLiEAM/PdMxwottvTOkEzycSwuj0Arbbx3nFZhnuafQD3nFtuZ8D8Gjo1vqB2%2Bd6c3P5ptunNL5DXCYTjxQzhjcGIZA/uxiQkD9NmTCmWA6f9D9wrxVQ//eaVnyaKaJfKWUHKHEPWTV0VgFzUKI5cnFQFsVmlWl98poRsMUHB5ItoDcStE1%2BAUY4DgE8Auo6wvpxQwQQDyI5cJo8DtFLAP8etR00CqoMD/RtBQliC6CzgsDcC6DSCLByChtR0uDE10AWAvMEDYc/MCBR8QALoIATczcLdyIrcZNfdmkL9A86dmlnsi0Lt%2B0sCh1vQlCWAVCcU1CLA6Ch0lgYDuDuCBC2CdtuDL0etrCD9KIOAVhaBOB/BeA/AOAtBSBUBOAtErBh8wJ1gy9dgeBSACBNAHCVhkwQAzBHxnsEguBpxpx/AzAEgNBHwdhHwNBEj9BOBJBXCwjPDOBeAFAQAwlQj3CHDSA4BYAkASdzQyAKAg9TQ6iQBgAuAdgv0sAIpNgAA1PATALiciR7TgYIwrHCYgYoiAaIfI8nZgUkYY3gGYpoEkciaIbQK4eY0gE0LNAgciXdEkfIrAGRYAU/SMYo7gXgLASEIwcQco0gfAN0boS4M4jw3CLoLwHCDYjWGofIvdIVUkDwLAfIlPFgeYlYKgAwYABQXo/owYxgDY/gQQEQMQdgKQGQQQRQFQdQW43QL9AwIwFATVfQNKYoyAFYVAZIYiTgDhSiMZQuLqM8PGTsDhciHYI4DhSEDYGEcGBQZMEkAwHhXgVAYkVEIneAFYToB0PwCAVwSYPwL9EIOYMoCoPQAoDIAQWUlUtINUhgAYJU4YL9CUuoXoCYTwNoPQQ0noGYXUoYeIA0mYDUu0voa0hYW08UtYDYFExw5wvI24rwjgXLR8acDhacSQZxZAMUNo57GscQ/Aa4IfdopYXgMorQYw0gSIrgW3fwfwFI6cR8KyaI/wSQNonYQIJwjgXI0gNwjwv0ookokIsIlYKoxAFAZpM0egeoygWo9slotojookJCaEgYoY84vgOgMYiYqY24xYuYkc6c5Y1Y9YkcrY9VXYq0A4zAI4k42WDYy4wwYAG4jw%2B4g0J4/I141VD4kcr4ss4I34jKEkAErYDw4E0EvgCEqEvoocuEkchE4QPPFE6QH8jEtQfI3QEDPE4wQk34kkkyTwikzIM46k2kkGekl5Jk8ibKYMdkpoRMLqHkvk/lTAQU4UiUEhMU6oWoTIFwSSB0oISSZ05Ur9VUuoGipizIei/U8ig0AQY0loU03IA0/USUni9i202we0viuUsSp0xUm0iQN0gIz07IjgFwys/Iv0gMoMkMsMiMvXaM3AQgX0IIxM%2Bs8o1MyIoSfXBInYUebMqyLWBIR8R8BIJSisqswUwo2wOs5MiopsiAJAIgTwcgSgJoSEjykKhQNHcIWgIQBANfNw4IrsuIRpNgTgVQQM4M0M4AcM2sXS3gWkAykUvQH8pE8QVEwCpQYC7EqI0gFgAQa1VAfS64AACSDAsCrweHeNQFhM/A2NqtKQatjJIG6t6rqrQAaG%2BA2K%2BDCA8qmoYEipqBirio2ICtoGUlHzSGtShBjAYGTFICQSYGSBfLLJUrcoKI4HIiEHNwtQgA0Ge38H10GjSs0syuysjL0sGsQIBHIw8CaPbPjMzyTIbIiJAB2Csme0SKsnzKsgcp2ASH8A0FRLLNcrUpmq8qBqUrMB9OrI8u8tTOJHSGcEkCAA%3D)

**Comment by JanLJL** [comment]
Hi @TiborGY ,

thanks for opening that issue, there is a bug in the data base (on the OSACA side) of the ICX machine file that caused that error. I will fix it soon and open a PR for updating the version used in godbolt, which might take a few days.
I saw you are using the `march=skylake` flag in your compiler, so you might want to use SKX (instead of the default ICX) architecture for OSACA anyway (using `--arch skx`), this one should work in the current version already.
